services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Maispace\MaiTheme\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Event/*'
      - '../Classes/Exception/*'

  Maispace\MaiTheme\Service\BackendThemeService:
    public: true
    shared: true

  Maispace\MaiTheme\Service\AssetRegistrationService:
    public: true
    shared: true
